# azure-pipelines.yml

trigger:
  - main  # Adjust the branch name as needed

variables:
  # Hardcoded Values
  subscription: adbc02d4-9ebd-4feb-b958-2d1b9c1130a2
  tenant: bded4dcc-cc45-4b9a-bda4-b1430f6c7f6f
  clientId: 6cef0901-0ae1-4413-9004-491ad43e9e7d
  subscriptionId: adbc02d4-9ebd-4feb-b958-2d1b9c1130a2
  tenantId: bded4dcc-cc45-4b9a-bda4-b1430f6c7f6f
  activeDirectoryEndpointUrl: https://login.microsoftonline.com
  resourceManagerEndpointUrl: https://management.azure.com/
  activeDirectoryGraphResourceId: https://graph.windows.net/
  sqlManagementEndpointUrl: https://management.core.windows.net:8443/
  galleryEndpointUrl: https://gallery.azure.com/
  managementEndpointUrl: https://management.core.windows.net/

stages:
  - stage: Setup
    displayName: 'Setup Environment'
    jobs:
      - job: DockerLogin
        displayName: 'Docker Login to Azure Container Registry'
        steps:
          - task: Bash@3
            displayName: 'Docker Login'
            inputs:
              targetType: 'inline'
              script: |
                echo "${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_PASSWORD }}" | docker login cakeryregistry.azurecr.io -u cakeryregistry --password-stdin

  - stage: Deploy
    displayName: 'Deploy Application'
    dependsOn: Setup
    jobs:
      - job: DeployJob
        displayName: 'Deploy to Azure'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'YourAzureServiceConnection'  # Replace with your Azure service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account set --subscription $(subscription)
                az role assignment list --assignee $(clientId) --output table
                # Add additional deployment commands here
