name: Azure Web App Deployment (Main)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_BACK_WEBAPP_NAME: CakeryBackendApp
      AZURE_BACK_RESOURCE_GROUP: CakeryResourceGroup
      AZURE_BACK_REGISTRY_SERVER_URL: cakeryregistry.azurecr.io
      AZURE_BACK_REGISTRY_USERNAME: ${{ secrets.AZURE_BACK_REGISTRY_USERNAME }}
      AZURE_BACK_REGISTRY_PASSWORD: ${{ secrets.AZURE_BACK_REGISTRY_PASSWORD }}
      DOCKER_IMAGE: flask-api-image:v1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_BACK_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.AZURE_BACK_REGISTRY_PASSWORD }} | docker login ${{ env.AZURE_BACK_REGISTRY_SERVER_URL }} -u ${{ env.AZURE_BACK_REGISTRY_USERNAME }} --password-stdin

    - name:  Build and Push Docker Image
      run: |
        docker build -t ${{ env.AZURE_BACK_REGISTRY_SERVER_URL }}/${{ env.DOCKER_IMAGE }} .
        docker push ${{ env.AZURE_BACK_REGISTRY_SERVER_URL }}/${{ env.DOCKER_IMAGE }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_BACK_WEBAPP_NAME }}
        resource-group-name: ${{ env.AZURE_BACK_RESOURCE_GROUP }}
        images: ${{ env.AZURE_BACK_REGISTRY_SERVER_URL }}/${{ env.DOCKER_IMAGE }}
