name: CI/CD Pipeline

trigger:
  - main

variables:
  dockerRegistryServiceConnection: 'cakeryregistry.azurecr.io'
  imageRepository: 'flask-api-image'
  containerRegistry: 'cakeryregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: 'latest'

stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(containerRegistry)
      env:
        DOCKER_PASSWORD: $(AZURE_BACK_DOCKER_REGISTRY_SERVER_PASSWORD)

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to Azure Web App
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'adbc02d4-9ebd-4feb-b958-2d1b9c1130a2'
        appName: 'CakeryBackendApp'
        containers: $(containerRegistry)/$(imageRepository):$(tag)
