name: CI/CD Pipeline for Flask Backend

on:
  push:
    branches:
      - Development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_URL }}
          username: ${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_USERNAME }}
          password: ${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_URL }}/flask-api-image:latest .
          docker push ${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_URL }}/flask-api-image:latest

      # Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_BACK_WEBAPP_NAME }}
          slot-name: production
          images: ${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_URL }}/flask-api-image:latest
