name: CI/CD Pipeline for Flask Backend

on:
  push:
    branches:
      - Development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Step 2: Azure Container Registry Login
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: cakeryregistry.azurecr.io
          username: cakeryregistry
          password: ${{ secrets.AZURE_BACK_DOCKER_REGISTRY_SERVER_PASSWORD }}

      # ✅ Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t cakeryregistry.azurecr.io/flask-api-image:latest .
          docker push cakeryregistry.azurecr.io/flask-api-image:latest

      # ✅ Step 4: Azure Web App Deployment
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: CakeryBackendApp
          resource-group-name: CakeryResourceGroup
          slot-name: production
          images: cakeryregistry.azurecr.io/flask-api-image:latest

      # ✅ Step 5: Verify Deployment (Optional)
      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully!"
