name: Backend API Ci/CD

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cakeryregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_850b01ec45ef41208cb42e434f4ed852 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e98ae8dfdbdc41af98fb3773989f5f46 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cakeryregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_850b01ec45ef41208cb42e434f4ed852 }}/flask-api-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CakeryBackendApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ace821279ad04ca580481e1f0d2ca9c6 }}
        images: 'cakeryregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_850b01ec45ef41208cb42e434f4ed852 }}/flask-api-image:${{ github.sha }}'
