name: Backenddeployment CI/CD

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://cakeryregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_850b01ec45ef41208cb42e434f4ed852 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_e98ae8dfdbdc41af98fb3773989f5f46 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cakeryregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_850b01ec45ef41208cb42e434f4ed852 }}/flask-api-image:${{ github.sha }}
          file: ./Dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Backenddeployment'
          slot-name: 'Production'
